import { useState } from 'react'
import { AlertTriangle, CheckCircle2, ChevronRight, Plus, Trash2 } from 'lucide-react'
import { products } from '../data'
import Modal from '../components/Modal'
import { useTranslation } from '../lib/i18n'

type Props = { onToast: (message: string) => void }
export default function FreshnessPage({ onToast }: Props) {
  const { t } = useTranslation(); const [wasteModal, setWasteModal] = useState(false); const [tab, setTab] = useState('queue')
  const tabs = [{ id: 'queue', label: 'freshness.queue' }, { id: 'waste', label: 'freshness.wasteLog' }, { id: 'batches', label: 'freshness.batches' }]
  const submitWaste = (event: React.FormEvent) => { event.preventDefault(); setWasteModal(false); onToast(t('freshness.wasteSaved')) }
  return <div className="page-content">
    <section className="freshness-hero glass-panel"><div className="freshness-hero-copy"><span className="section-kicker">{t('freshness.fefo')}</span><h2>{t('freshness.protect')}</h2><p>{t('freshness.description')}</p><div><button className="primary-button" onClick={() => setWasteModal(true)}><Plus size={17} /> {t('freshness.recordWaste')}</button><button className="secondary-button" onClick={() => onToast(t('freshness.reportExported'))}>{t('freshness.exportReport')}</button></div></div><div className="freshness-score"><svg viewBox="0 0 120 120"><circle cx="60" cy="60" r="48" /><circle className="score-progress" cx="60" cy="60" r="48" /></svg><div><strong>94%</strong><span>{t('freshness.score')}</span></div><small><CheckCircle2 size={14} /> {t('freshness.healthy')}</small></div></section>
    <section className="kpi-grid compact-kpis freshness-kpis"><article className="mini-kpi glass-panel"><span>{t('freshness.freshSellable')}</span><strong>181 {t('common.units')}</strong><small className="green-text">{t('freshness.inventoryPercent')}</small></article><article className="mini-kpi glass-panel"><span>{t('freshness.expiresToday')}</span><strong className="coral-text">3 {t('common.units')}</strong><small>$90 {t('catalog.retailValue', { value: '' }).replace('$', '').trim()}</small></article><article className="mini-kpi glass-panel"><span>{t('freshness.expiresTomorrow')}</span><strong className="amber-text">2 {t('common.units')}</strong><small>$64 {t('catalog.retailValue', { value: '' }).replace('$', '').trim()}</small></article><article className="mini-kpi glass-panel"><span>{t('freshness.wasteWeek')}</span><strong>$38.00</strong><small className="green-text">{t('freshness.lastWeek')}</small></article></section>
    <section className="filter-tabs standalone-tabs">{tabs.map((item) => <button key={item.id} className={tab === item.id ? 'active' : ''} onClick={() => setTab(item.id)}>{t(item.label)}</button>)}</section>
    {tab === 'queue' && <section className="glass-panel freshness-table table-responsive"><div className="panel-heading"><div><span className="section-kicker">{t('freshness.priorityList')}</span><h2>{t('freshness.sellFirst')}</h2></div><span className="queue-updated"><i /> {t('freshness.updated')}</span></div><div className="freshness-row freshness-head"><span>{t('freshness.priority')}</span><span>{t('freshness.productBatch')}</span><span>{t('freshness.made')}</span><span>{t('catalog.bestBeforeLabel')}</span><span>{t('freshness.onHand')}</span><span>{t('freshness.valueRisk')}</span><span>{t('freshness.action')}</span></div>{[...products].sort((a, b) => priority(a.status) - priority(b.status)).map((product, index) => <div className="freshness-row" key={product.id}><span className={`priority-number p${Math.min(index + 1, 4)}`}>{index + 1}</span><div className="catalog-product"><span className="catalog-image" style={{ backgroundPosition: product.imagePosition }} /><div><strong>{product.name}</strong><small>{t('freshness.batch', { id: 2000 + product.id })}</small></div></div><span>{product.madeAt.replace(', 2026', '')}</span><span><strong>{product.bestBefore.replace(', 2026', '')}</strong><small className={`block-note ${product.status === 'Expires today' ? 'coral-text' : ''}`}>{statusLabel(t, product.status)}</small></span><strong>{product.stock} {t('common.units')}</strong><strong>${(product.stock * product.price).toFixed(2)}</strong>{product.status === 'Expired' ? <button className="text-button coral-text" onClick={() => setWasteModal(true)}>{t('freshness.writeOff')} <ChevronRight size={15} /></button> : <button className="text-button" onClick={() => onToast(t('freshness.flagged', { name: product.name }))}>{t('freshness.prioritize')} <ChevronRight size={15} /></button>}</div>)}</section>}
    {tab === 'waste' && <section className="glass-panel simple-data-card"><div className="panel-heading"><div><span className="section-kicker">{t('freshness.recordedLoss')}</span><h2>{t('freshness.wasteLog')}</h2></div><button className="primary-button" onClick={() => setWasteModal(true)}><Plus size={16} /> {t('freshness.recordWaste')}</button></div><div className="waste-log-row table-head"><span>{t('freshness.date')}</span><span>{t('dashboard.product')}</span><span>{t('freshness.quantity')}</span><span>{t('freshness.reason')}</span><span>{t('freshness.costImpact')}</span><span>{t('freshness.recordedBy')}</span></div><div className="waste-log-row"><span>Aug 19 · 6:14 PM</span><strong>Cocoa Mini</strong><span>2 {t('common.units')}</span><span className="reason-pill">{t('dashboard.expiresToday')}</span><strong>$14.00</strong><span>Sophea</span></div><div className="waste-log-row"><span>Aug 18 · 4:32 PM</span><strong>Berry Basque</strong><span>1 {t('common.unit')}</span><span className="reason-pill">{t('freshness.damaged')}</span><strong>$18.00</strong><span>Dara</span></div><div className="waste-log-row"><span>Aug 17 · 7:02 PM</span><strong>Vanilla Cupcake</strong><span>2 {t('common.units')}</span><span className="reason-pill">{t('freshness.quality')}</span><strong>$6.00</strong><span>Sophea</span></div></section>}
    {tab === 'batches' && <section className="batch-grid">{products.slice(0, 4).map((product) => <article className="glass-panel batch-card" key={product.id}><div><span className="catalog-image" style={{ backgroundPosition: product.imagePosition }} /><span className={`freshness-badge ${product.status === 'Fresh' ? 'fresh' : 'warning'}`}>{statusLabel(t, product.status)}</span></div><span>{t('freshness.batch', { id: 2000 + product.id })}</span><h3>{product.name}</h3><dl><div><dt>{t('freshness.produced')}</dt><dd>{product.madeAt.replace(', 2026', '')}</dd></div><div><dt>{t('freshness.initialYield')}</dt><dd>{product.stock + product.sold} {t('common.units')}</dd></div><div><dt>{t('freshness.sold')}</dt><dd>{product.sold} {t('common.units')}</dd></div><div><dt>{t('freshness.remaining')}</dt><dd>{product.stock} {t('common.units')}</dd></div></dl></article>)}</section>}
    <Modal open={wasteModal} onClose={() => setWasteModal(false)} eyebrow={t('freshness.inventoryAdjustment')} title={t('freshness.recordWasteTitle')} size="small"><form className="modal-form" onSubmit={submitWaste}><div className="form-grid"><label><span>{t('freshness.productBatch')}</span><select required defaultValue=""><option value="" disabled>{t('freshness.selectProduct')}</option>{products.map((product) => <option key={product.id}>{product.name}</option>)}</select></label><div className="form-grid two-columns"><label><span>{t('freshness.quantity')}</span><input type="number" min="1" defaultValue="1" required /></label><label><span>{t('freshness.reason')}</span><select><option>{t('dashboard.expiresToday')}</option><option>{t('freshness.damaged')}</option><option>{t('freshness.qualityIssue')}</option><option>{t('freshness.staffMeal')}</option></select></label></div><label><span>{t('freshness.noteOptional')}</span><textarea placeholder={t('freshness.auditContext')} rows={3} /></label></div><div className="form-notice warning"><AlertTriangle size={17} /><span>{t('freshness.wasteWarning')}</span></div><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setWasteModal(false)}>{t('common.cancel')}</button><button className="primary-button"><Trash2 size={16} /> {t('freshness.recordWaste')}</button></div></form></Modal>
  </div>
}
function priority(status: string) { return status === 'Expires today' ? 0 : status === '1 day left' ? 1 : status === 'Fresh' ? 2 : 3 }
function statusLabel(t: (key: string, variables?: Record<string, string | number>) => string, status: string) { return status === 'Fresh' ? t('dashboard.freshStatus') : status === '1 day left' ? t('dashboard.oneDayLeft') : status === 'Expires today' ? t('dashboard.expiresToday') : t('catalog.expired') }
