import { useMemo, useState } from 'react'
import { Banknote, CalendarDays, Download, MoreHorizontal, ReceiptText, RotateCcw, ScanLine, Search } from 'lucide-react'
import { type Order } from '../data'
import { useTranslation } from '../lib/i18n'
import { useAdminData } from '../lib/data'

type OrdersPageProps = { selectedId: string | null; onSelect: (id: string | null) => void; onToast: (message: string) => void }
export default function OrdersPage({ selectedId, onSelect, onToast }: OrdersPageProps) {
  const { t } = useTranslation(); const { orders } = useAdminData(); const [query, setQuery] = useState(''); const [status, setStatus] = useState('all'); const selected = orders.find((order) => order.id === selectedId) || null
  const statuses = [{ id: 'all', label: 'common.all' }, { id: 'Completed', label: 'common.success' }, { id: 'Refunded', label: 'common.refund' }, { id: 'Voided', label: 'orders.voided' }]
  const visible = useMemo(() => orders.filter((order) => { const matches = `${order.id} ${order.cashier} ${order.payment}`.toLowerCase().includes(query.toLowerCase()); return matches && (status === 'all' || order.status === status) }), [query, status])
  const exportOrders = () => { const rows = ['Order,Time,Cashier,Payment,Status,Total', ...visible.map((order) => `${order.id},${order.time},${order.cashier},${order.payment},${order.status},${order.total}`)]; const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([rows.join('\n')], { type: 'text/csv' })); link.download = 'orders-2026-08-20.csv'; link.click(); URL.revokeObjectURL(link.href); onToast(t('orders.reportExported')) }
  return <div className="page-content">
    <section className="kpi-grid compact-kpis"><article className="mini-kpi glass-panel"><span>{t('orders.grossSales')}</span><strong>$1,254.50</strong><small>{t('orders.beforeRefunds')}</small></article><article className="mini-kpi glass-panel"><span>{t('dashboard.netSales')}</span><strong>$1,224.50</strong><small className="green-text">{t('orders.netVsYesterday')}</small></article><article className="mini-kpi glass-panel"><span>{t('orders.transactions')}</span><strong>47</strong><small>{t('orders.completedRefunded')}</small></article><article className="mini-kpi glass-panel"><span>{t('orders.refundRate')}</span><strong>2.4%</strong><small>{t('orders.normalRange')}</small></article></section>
    <section className="page-toolbar catalog-toolbar"><div className="filter-row"><label className="inline-search"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t('orders.search')} /></label><div className="filter-tabs">{statuses.map((item) => <button key={item.id} className={status === item.id ? 'active' : ''} onClick={() => setStatus(item.id)}>{t(item.label)}</button>)}</div></div><div className="toolbar-actions"><button className="secondary-button"><CalendarDays size={16} /> {t('common.today')}</button><button className="secondary-button" onClick={exportOrders}><Download size={16} /> {t('common.export')}</button></div></section>
    <section className={`orders-layout ${selected ? 'with-detail' : ''}`}><div className="glass-panel orders-full-table table-responsive"><div className="order-full-row table-head"><span>{t('dashboard.order')}</span><span>{t('dashboard.time')}</span><span>{t('dashboard.cashier')}</span><span>{t('orders.items')}</span><span>{t('dashboard.payment')}</span><span>{t('catalog.status')}</span><span>{t('orders.total')}</span><span /></div>{visible.map((order) => <button className={`order-full-row ${selectedId === order.id ? 'selected' : ''}`} key={order.id} onClick={() => onSelect(order.id)}><strong>{order.id}</strong><span><strong>{order.time}</strong><small>{order.date}</small></span><span>{order.cashier}</span><span>{order.items}</span><span className="payment-pill">{order.payment === 'KHQR' ? <ScanLine size={14} /> : <Banknote size={14} />}{paymentLabel(t, order.payment)}</span><span className={`status-badge ${order.status === 'Completed' ? 'success' : order.status === 'Refunded' ? 'warning' : 'neutral'}`}><i />{statusLabel(t, order.status)}</span><strong className="numeric">${order.total.toFixed(2)}</strong><MoreHorizontal size={17} /></button>)}</div>{selected && <OrderDetail order={selected} onClose={() => onSelect(null)} onToast={onToast} />}</section>
  </div>
}
function OrderDetail({ order, onClose, onToast }: { order: Order; onClose: () => void; onToast: (message: string) => void }) {
  const { t } = useTranslation()
  return <aside className="glass-panel order-detail"><div className="order-detail-head"><div><span>{t('orders.orderDetails')}</span><h2>{order.id}</h2></div><button className="text-button" onClick={onClose}>{t('common.close')}</button></div><div className="receipt-meta"><div><span>{t('orders.placed')}</span><strong>{order.time}, {order.date}</strong></div><div><span>{t('dashboard.cashier')}</span><strong>{order.cashier}</strong></div><div><span>{t('dashboard.payment')}</span><strong>{paymentLabel(t, order.payment)}</strong></div><div><span>{t('catalog.status')}</span><strong className={order.status === 'Completed' ? 'green-text' : 'amber-text'}>{statusLabel(t, order.status)}</strong></div></div><div className="receipt-lines"><span>{t('orders.items')}</span>{order.detail.map((item) => <div key={item}><strong>{item}</strong><span>${(order.total / order.detail.length).toFixed(2)}</span></div>)}</div><div className="receipt-total"><span><small>{t('orders.subtotal')}</small><strong>${order.total.toFixed(2)}</strong></span><span><small>{t('orders.discount')}</small><strong>—</strong></span><span className="grand-total"><small>{t('orders.total')}</small><strong>${order.total.toFixed(2)}</strong></span></div><div className="receipt-confirmation"><ReceiptText size={17} /><span><strong>{t('orders.paymentConfirmed')}</strong><small>{t('orders.recordedBy', { cashier: order.cashier, time: order.time })}</small></span></div><div className="detail-actions"><button className="secondary-button" onClick={() => onToast(t('orders.receiptQueued'))}><ReceiptText size={16} /> {t('common.printReceipt')}</button><button className="danger-outline" onClick={() => onToast(t('orders.refundOpened'))}><RotateCcw size={16} /> {t('common.refund')}</button></div></aside>
}
function paymentLabel(t: (key: string, variables?: Record<string, string | number>) => string, payment: string) { return payment === 'KHQR' ? t('payment.khqr') : t('payment.cash') }
function statusLabel(t: (key: string, variables?: Record<string, string | number>) => string, status: string) { return status === 'Completed' ? t('common.success') : status === 'Refunded' ? t('common.refund') : t('orders.voided') }
