import { useMemo, useState } from 'react'
import { Archive, ChevronDown, Columns3, Download, Edit3, MoreHorizontal, Plus, Search, SlidersHorizontal } from 'lucide-react'
import { products, type Product } from '../data'
import Modal from '../components/Modal'
import { translateCategory, useTranslation } from '../lib/i18n'

type ProductsPageProps = { onAdd: () => void; onToast: (message: string) => void }
export default function ProductsPage({ onAdd, onToast }: ProductsPageProps) {
  const { t } = useTranslation(); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('all'); const [editing, setEditing] = useState<Product | null>(null); const [view, setView] = useState<'table' | 'grid'>('table')
  const filters = [{ id: 'all', label: 'catalog.allProducts' }, { id: 'active', label: 'common.active' }, { id: 'risk', label: 'catalog.freshnessRisk' }, { id: 'out', label: 'catalog.outOfStock' }]
  const visible = useMemo(() => products.filter((product) => { const matchesQuery = `${product.name} ${translateCategory(t, product.category)}`.toLowerCase().includes(query.toLowerCase()); if (filter === 'active') return matchesQuery && product.active; if (filter === 'risk') return matchesQuery && ['1 day left', 'Expires today', 'Expired'].includes(product.status); if (filter === 'out') return matchesQuery && product.stock === 0; return matchesQuery }), [query, filter])
  const saveEdit = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setEditing(null); onToast(t('catalog.saved')) }
  return <div className="page-content">
    <section className="catalog-summary"><div><span>{t('catalog.allProducts')}</span><strong>52</strong><small>{t('catalog.activeProducts', { count: 48 })}</small></div><div><span>{t('catalog.unitsOnHand')}</span><strong>186</strong><small>{t('catalog.retailValue', { value: '2,946' })}</small></div><div><span>{t('catalog.freshnessRisk')}</span><strong className="coral-text">5</strong><small>{t('catalog.retailValue', { value: '146' })}</small></div><div><span>{t('catalog.soldToday')}</span><strong>82</strong><small>{t('catalog.sellThroughPercent', { percent: 68 })}</small></div></section>
    <section className="page-toolbar catalog-toolbar"><div className="filter-row"><label className="inline-search"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t('catalog.search')} /></label><div className="filter-tabs">{filters.map((item) => <button className={filter === item.id ? 'active' : ''} onClick={() => setFilter(item.id)} key={item.id}>{t(item.label)}</button>)}</div></div><div className="toolbar-actions"><button className="icon-button" onClick={() => setView(view === 'table' ? 'grid' : 'table')} title={t('catalog.changeView')}><Columns3 size={18} /></button><button className="secondary-button"><SlidersHorizontal size={16} /> {t('catalog.filters')}</button><button className="primary-button" onClick={onAdd}><Plus size={17} /> {t('header.addCake')}</button></div></section>
    {view === 'table' ? <section className="glass-panel catalog-table table-responsive"><div className="catalog-table-head catalog-row"><label><input type="checkbox" /> {t('catalog.product')}</label><span>{t('catalog.freshness')}</span><span>{t('catalog.stock')}</span><span>{t('catalog.price')}</span><span>{t('catalog.today')}</span><span>{t('catalog.status')}</span><span /></div>{visible.map((product) => <div className="catalog-row" key={product.id}><div className="catalog-product"><input type="checkbox" /><span className="catalog-image" style={{ backgroundPosition: product.imagePosition }} /><div><strong>{product.name}</strong><small>{translateCategory(t, product.category)} · {t('catalog.sku', { id: String(product.id).padStart(3, '0') })}</small></div></div><div><span className={`freshness-badge ${statusClass(product.status)}`}>{statusLabel(t, product.status)}</span><small className="block-note">{t('catalog.bestBefore', { date: product.bestBefore.replace(', 2026', '') })}</small></div><div className="stock-cell"><strong>{product.stock}</strong><span>{t('common.units')}</span></div><strong className="numeric">${product.price.toFixed(2)}</strong><div><strong>{t('catalog.sold', { count: product.sold })}</strong><small className="block-note">${product.revenue}</small></div><span className={`status-badge ${product.active ? 'success' : 'neutral'}`}><i />{product.active ? t('common.active') : t('common.archived')}</span><button className="icon-button" onClick={() => setEditing(product)} aria-label={`${t('common.edit')} ${product.name}`}><MoreHorizontal size={18} /></button></div>)}{visible.length === 0 && <div className="empty-state"><Search size={24} /><strong>{t('catalog.noProducts')}</strong><span>{t('catalog.trySearchFilter')}</span></div>}<div className="table-footer"><span>{t('catalog.showing', { shown: visible.length })}</span><div><button disabled>{t('common.previous')}</button><button>1</button><button>2</button><button>{t('common.next')}</button></div></div></section> : <section className="catalog-card-grid">{visible.map((product) => <article className="glass-panel catalog-card" key={product.id}><div className="catalog-card-image" style={{ backgroundPosition: product.imagePosition }}><span className={`freshness-badge ${statusClass(product.status)}`}>{statusLabel(t, product.status)}</span><button className="icon-button" onClick={() => setEditing(product)} aria-label={`${t('common.edit')} ${product.name}`}><MoreHorizontal size={18} /></button></div><div className="catalog-card-copy"><span>{translateCategory(t, product.category)}</span><h3>{product.name}</h3><div><strong>${product.price}</strong><span>{product.stock} {t('common.units')}</span></div></div></article>)}</section>}
    <Modal open={Boolean(editing)} onClose={() => setEditing(null)} eyebrow={t('catalog.catalogItem')} title={t('catalog.editProduct')} size="medium">{editing && <form className="modal-form" onSubmit={saveEdit}><div className="edit-product-summary"><span className="edit-product-image" style={{ backgroundPosition: editing.imagePosition }} /><div><span>{t('catalog.sku', { id: String(editing.id).padStart(3, '0') })}</span><strong>{editing.name}</strong><small>{t('catalog.created', { date: editing.madeAt })}</small></div></div><div className="form-grid two-columns"><label><span>{t('catalog.productName')}</span><input defaultValue={editing.name} required /></label><label><span>{t('catalog.category')}</span><select defaultValue={editing.category}><option value="Signature Cakes">{t('catalog.signature')}</option><option value="Chocolate">{t('catalog.chocolate')}</option><option value="Cheesecakes">{t('catalog.cheesecakes')}</option><option value="Birthday Cakes">{t('catalog.birthday')}</option><option value="Mini Cakes">{t('catalog.mini')}</option></select><ChevronDown size={15} /></label><label><span>{t('catalog.priceUsd')}</span><input type="number" step="0.01" defaultValue={editing.price} required /></label><label><span>{t('catalog.stockQuantity')}</span><input type="number" defaultValue={editing.stock} required /></label><label><span>{t('catalog.madeAt')}</span><input type="date" defaultValue="2026-08-20" /></label><label><span>{t('catalog.bestBeforeLabel')}</span><input type="date" defaultValue="2026-08-23" /></label></div><label className="toggle-field"><span><strong>{t('catalog.availableForSale')}</strong><small>{t('catalog.visibleSale')}</small></span><input type="checkbox" defaultChecked={editing.active} /><i /></label><div className="modal-actions split-actions"><button type="button" className="danger-text-button"><Archive size={16} /> {t('catalog.archive')}</button><span><button type="button" className="secondary-button" onClick={() => setEditing(null)}>{t('common.cancel')}</button><button className="primary-button"><Edit3 size={16} /> {t('catalog.saveChanges')}</button></span></div></form>}</Modal>
  </div>
}
function statusClass(status: Product['status']) { return status === 'Fresh' ? 'fresh' : status === '1 day left' ? 'warning' : 'danger' }
function statusLabel(t: (key: string, variables?: Record<string, string | number>) => string, status: string) { return status === 'Fresh' ? t('dashboard.freshStatus') : status === '1 day left' ? t('dashboard.oneDayLeft') : status === 'Expires today' ? t('dashboard.expiresToday') : t('catalog.expired') }
