<?php
namespace App\Services;
use App\Reporting\DateRange;
use App\Models\{Order,OrderItem,OrderPayment};
use Illuminate\Support\Facades\Cache; use Illuminate\Support\Facades\DB;
final class ReportingService {
 private function paid(DateRange $r){return Order::query()->where('status','Completed')->where('payment_status','paid')->whereBetween('created_at',[$r->from,$r->to]);}
 public function summary(array $input):array { $r=DateRange::from($input); return Cache::remember('report:summary:'.$r->from.$r->to,45,function()use($r){$q=$this->paid($r);$x=$q->selectRaw('COALESCE(SUM(subtotal_cents),0) gross,COALESCE(SUM(discount_amount_cents),0) discounts,COALESCE(SUM(total_cents),0) net,COUNT(*) count')->first();$corr=Order::whereIn('status',['Refunded','Voided'])->whereBetween('created_at',[$r->from,$r->to])->selectRaw('COALESCE(SUM(-total_cents),0) amount')->value('amount');$gross=(int)$x->gross;$discount=(int)$x->discounts;$net=(int)$x->net;return ['grossSalesCents'=>$gross,'totalDiscountsCents'=>$discount,'netSalesBeforeCorrectionsCents'=>$gross-$discount,'refundsCents'=>Order::where('status','Refunded')->whereBetween('created_at',[$r->from,$r->to])->sum(DB::raw('-total_cents')),'voidsCents'=>Order::where('status','Voided')->whereBetween('created_at',[$r->from,$r->to])->sum(DB::raw('-total_cents')),'netRevenueCents'=>$net-(int)$corr,'completedOrderCount'=>(int)$x->count,'heldOrderCount'=>Order::where('status','Held')->whereBetween('created_at',[$r->from,$r->to])->count(),'averageOrderValueCents'=>$x->count?(int)intdiv($net-(int)$corr,$x->count):0,'cashRevenueCents'=>$this->paid($r)->where('payment','Cash')->sum('total_cents'),'qrRevenueCents'=>$this->paid($r)->where('payment','KHQR')->sum('total_cents')];}); }
 public function trend(array $input):array{$r=DateRange::from($input);$format=($input['granularity']??'day')==='month'?'%Y-%m':'%Y-%m-%d';$rows=$this->paid($r)->selectRaw("DATE_FORMAT(CONVERT_TZ(created_at,'UTC','Asia/Phnom_Penh'),?) bucket,SUM(subtotal_cents) gross,SUM(discount_amount_cents) discounts,SUM(total_cents) net",[$format])->groupBy('bucket')->pluck('net','bucket');$out=[];$cursor=$r->from;while($cursor<=$r->to){$key=$cursor->format($format==='%Y-%m'?'Y-m':'Y-m-d');$out[]=['period'=>$key,'netRevenueCents'=>(int)($rows[$key]??0)];$cursor=$format==='%Y-%m'?$cursor->addMonth():$cursor->addDay();}return $out;}
 public function payments(array $input):array{$r=DateRange::from($input);return OrderPayment::where('status','confirmed')->whereBetween('confirmed_at',[$r->from,$r->to])->select('method')->selectRaw('COUNT(*) transactions,SUM(amount_usd_cents) amount_usd_cents,SUM(COALESCE(tendered_usd_cents,0)) tendered_usd_cents,SUM(COALESCE(tendered_khr,0)) tendered_khr,SUM(COALESCE(change_usd_cents,0)) change_usd_cents,SUM(COALESCE(change_khr,0)) change_khr,SUM(settlement_rounding_khr) settlement_rounding_khr')->groupBy('method')->get()->toArray();}
 public function products(array $input):array{$r=DateRange::from($input);$limit=$input['limit']??10;return OrderItem::join('orders','orders.id','=','order_items.order_id')->where('orders.status','Completed')->whereBetween('orders.created_at',[$r->from,$r->to])->select('order_items.product_id','order_items.description as snapshotName','order_items.category_snapshot')->selectRaw('SUM(quantity) quantity,SUM(line_subtotal_cents) grossRevenueCents,SUM(line_discount_cents) discountsCents,SUM(line_total_cents) netRevenueCents')->groupBy('order_items.product_id','order_items.description','order_items.category_snapshot')->orderByDesc('netRevenueCents')->limit($limit)->get()->toArray();}
 public function categories(array $input):array{$r=DateRange::from($input);return OrderItem::join('orders','orders.id','=','order_items.order_id')->where('orders.status','Completed')->whereBetween('orders.created_at',[$r->from,$r->to])->selectRaw("COALESCE(NULLIF(category_snapshot,''),'Unknown / archived') category,SUM(quantity) units,SUM(line_total_cents) netRevenueCents")->groupBy('category_snapshot')->get()->toArray();}
 public function peakHours(array $input):array{$r=DateRange::from($input);return $this->paid($r)->selectRaw('HOUR(CONVERT_TZ(created_at,"UTC","Asia/Phnom_Penh")) hour,COUNT(*) orders,SUM(total_cents) revenueCents')->groupBy('hour')->orderBy('hour')->get()->toArray();}
 public function cashiers(array $input):array{$r=DateRange::from($input);return $this->paid($r)->join('employees','employees.id','=','orders.cashier_id')->selectRaw('cashier_id,employees.name,COUNT(*) completedOrderCount,SUM(total_cents) netRevenueCents,SUM(discount_amount_cents) discountsCents')->groupBy('cashier_id','employees.name')->get()->toArray();}
 public function waste(array $input):array{$r=DateRange::from($input);return DB::table('inventory_waste_events')->whereBetween('recorded_at',[$r->from,$r->to])->selectRaw('reason,SUM(quantity) units,SUM(retail_value_cents) retailValueCents')->groupBy('reason')->get()->toArray();}
 public function customers(array $input):array{$r=DateRange::from($input);return $this->paid($r)->whereNotNull('customer_id')->selectRaw('customer_id,COUNT(*) orders,SUM(total_cents) netRevenueCents,MAX(created_at) lastOrderAt')->groupBy('customer_id')->orderByDesc('netRevenueCents')->limit($input['limit']??25)->get()->toArray();}
}
